dist: bionic

language: c

addons:
  apt:
    packages:
      - octave
      - liboctave-dev

matrix:
  include:
    - os: linux
    - os: osx
      before_install:
        - rvm use 2.6 # super-super-ugly travis stuff
        - brew update
        - brew install octave

script:
  - make -C contrib/octave clean test
