dist: bionic

language: c

addons:
  apt:
    packages:
      - octave
      - liboctave-dev

matrix:
  include:
    - os: linux
    - os: osx
      before_install:
        -  brew install octave

script:
  - make -C contrib/octave clean test
